Makefile: enable quic_unit_test only if kunit is enabled
Without kunit enabled, building quic_unit_test will report errors:

  ERROR: modpost: "__kunit_do_failed_assertion"
  ERROR: modpost: "__kunit_abort"
  ERROR: modpost: "kunit_binary_assert_format"

So fix the Makefile to build quic_unit_test only if kunit is built
and Kconfig to make IP_QUIC_TEST depend on NET_HANDSHAKE || KUNIT.

Signed-off-by: Xin Long <lucien.xin@gmail.com>